#!/bin/sh
#
# PROVIDE: ixautomation 
# REQUIRE: DAEMON dbus
# KEYWORD: FreeBSD

. /etc/rc.subr
. /etc/rc.conf

name="ixautomation"
rcvar="${name}_enable"
start_cmd="ixautomation_start"

start_pre_cmd="ixautomation_prestart"
{
  ixautomation_bridge="ixautomation"
  if [ -z "$ixautomation_iface" ] ; then
    echo "Failed to find an interface with internet access for bridge.  Please define an interface with ixautomation_iface= in /etc/rc.conf."
  fi
  if ! ifconfig ${ixautomation_bridge} >/dev/null 2>/dev/null ; then
    if ! ifconfig | grep member | grep ${ixautomation_iface} >/dev/null 2>/dev/null ; then
       echo "Adding "${ixautomation_iface}" to ixautomation bridge"
    else
      echo "Warning ${ixautomation_iface} is already in a bridge.  Please remove ${ixautomation_iface} from the bridge, or define an unused interface with ixautomation_iface in /etc/rc.conf."
      exit 1
    fi
  fi
}

ixautomation_start()
{
  ixautomation_bridge="ixautomation"
  if ! ifconfig ${ixautomation_bridge} >/dev/null 2>/dev/null ; then
    bridge=$(ifconfig bridge create)
    ifconfig ${bridge} name ${ixautomation_bridge} >/dev/null
  fi
  if ! ifconfig ${ixautomation_bridge} | grep -q "tap" >/dev/null 2>/dev/null ; then
    tap=$(ifconfig tap create)
    ifconfig ${ixautomation_bridge} addm ${tap}
  fi
  if ! ifconfig ${ixautomation_bridge} | grep -q "member: ${ixautomation_iface}" ; then
     ifconfig ${ixautomation_bridge} addm ${ixautomation_iface}
  fi
  if ! ifconfig ${ixautomation_bridge} | grep -q "member: ${ixautomation_iface}" ; then
     eerror "Warning ${ixautomation_iface} is already in a bridge.  Please remove ${ixautomation_iface} from the bridge, or define an unused interface with ixautomation_iface in /etc/rc.conf."
    exit 1
  fi
}

load_rc_config ${name}
run_rc_command "$1"
