#!/bin/sh
# Script to install preload.conf

PREFIX=${PKG_PREFIX-/usr/local}

if [ "$2" != "POST-INSTALL" ] ; then
   exit 0
fi

set +e

# If this is during staging, we can skip for now
echo $PREFIX | grep -q '/stage/'
if [ $? -eq 0 ] ; then
   exit 0
fi

# Configure vm-bhyve
sysrc -f /etc/rc.conf vm_enable="YES"
sysrc -f /etc/rc.conf vm_dir="/usr/local/ixautomation/vms"

# Copy over ixautomation.cfg.dist if it does not exist
if [ ! -f "/usr/local/etc/ixautomation.conf" ] ; then
  cp /usr/local/etc/ixautomation.cfg.dist /usr/local/etc/ixautomation.cfg
fi

find /usr/local/lib -name selenium | grep selenium >/dev/null
if [ "$?" != "0" ]; then
  echo "Installing selenium"
  pip-3.6 install selenium
fi

find /usr/local/lib -name xmlrunner | grep selenium >/dev/null
if [ "$?" != "0" ]; then
  echo "Installing unittest-xml-reporting"
  pip-3.6 install unittest-xml-reporting
fi

python3.6 -c "import ws4py" >/dev/null 2>/dev/null
if [ "$?" != "0" ]; then
  echo "Installing ws4py"
  rc_halt "pip3.6 install ws4py"
fi

python3.6 -c "import pytest" >/dev/null 2>/dev/null
if [ "$?" != "0" ]; then
  echo "Installing pytest"
  rc_halt "pip3.6 install pytest"
fi

python3.6 -c "import pytest_cache" >/dev/null 2>/dev/null
if [ "$?" != "0" ]; then
  echo "Installing pytest-cache"
  rc_halt "pip3.6 install pytest-cache"
fi

python3.6 -c "import pytest_capturelog" >/dev/null 2>/dev/null
if [ "$?" != "0" ]; then
  echo "Installing pytest-capturelog"
  rc_halt "pip3.6 install pytest-capturelog"
fi

python3.6 -c "import pytest_localserver" >/dev/null 2>/dev/null
if [ "$?" != "0" ]; then
  echo "Installing pytest-localserver"
  rc_halt "pip3.6 install pytest-localserver"
fi

python3.6 -c "import pytest_runner" >/dev/null 2>/dev/null
if [ "$?" != "0" ]; then
  echo "Installing pytest-runner"
  rc_halt "pip3.6 install pytest-runner"
fi

python3.6 -c "import pytest_cache" >/dev/null 2>/dev/null
if [ "$?" != "0" ]; then
  echo "Installing pytest-cache"
  rc_halt "pip3.6 install pytest-cache"
fi

python3.6 -c "import pytest_tornado" >/dev/null 2>/dev/null
if [ "$?" != "0" ]; then
  echo "Installing pytest-tornado"
  rc_halt "pip3.6 install pytest-tornado"
fi

python3.6 -c "import pytest_xdist" >/dev/null 2>/dev/null
if [ "$?" != "0" ]; then
  echo "Installing pytest-xdist"
  rc_halt "pip3.6 install pytest-xdist"
fi